### ISSUE TITLE
Allow users to register bots

### ISSUE THREAD

**Issue by Pharylon** [AiBattleground/BotWars#11]
I'm creating an issue for each server-related item outlined in Milestone 1.

This was included in the stuff I pushed that messed you guys up Thursday (sorry about that again!). We don't have the ability to upload DLLs, but I'm not sure if that's even feasible in the short run (once you let a DLL run in local code, the amount of malicious things you could do to win the game increases to nigh-infinity).

Patrick/Keith, does any more work need to be done on this? Or can it be closed?

**Comment by Dubman25** [comment]
Sorry, I just saw the extra detail under the milestones.  Yeah, I think
this issue can be closed at this point.

**Comment by Dubman25** [comment]
Close it up man!  Thanks.
