### ISSUE TITLE
Game Allows Diagonal Movement

### ISSUE THREAD

**Issue by Pharylon** [AiBattleground/BotWars#18]
Yeah. Kind of a big one. :)

I created a failing unit test.

**Comment by Dubman25** [comment]
I think there may be an even bigger issue.  Patrick and I did some testing
last Tuesday and Thursday to see if bots of a particular color had a
built-in advantage.  Our initial high level tests seemed to indicate that
was the case.  When the same bot fights itself, the blue version appeared
to win almost every time.

I think we need to add game logic unit testing to our list of tasks to do
for next Tuesday.

**Comment by Pharylon** [comment]
Interesting. I'm curious about that. I've seen stuff happen that I could have sworn was asymmetry, but I wasn't able to track anything down, and I was never sure if it was due to asymmetry in the way the bots play.

**Comment by Pharylon** [comment]
As @Pabreetzio pointed out last Thursday, in fact this allowed not just diagonal movement, but movement to anywhere. You could teleport across the board if you wanted. Definitely a big enough bug I wanted it done before tomorrow. I've fixed it.
