### ISSUE TITLE
GameState Questions

### ISSUE THREAD

**Issue by Pharylon** [AiBattleground/BotWars#19]
So, I was going in to update the Instructions section of the website with the information on our GameState class. (what's there now is pretty much just the Skookum information, but our object is slightly different). But while I was there, I saw two things that made me go "Hmmmmmmmmm." So, two questions:

First, what is the "turnId" field for?  I wanted to note in the Instructions if a field existed but just wasn't in use yet (like the Api Key), but note what it would be for in the future. But I'm not sure what the "turnId" field is for. It's not the turn number (that's turnsElapsed).

Also, does anyone object to me removing the "NullValueHandling = NullValueHandling.Ignore" property on the "winner" field? I know Patrick had to put this in because Skookum did it that way, but we don't have to do what Skookum did, and it shouldn't affect any existing bots. I'd rather pass "winner = null" if there isn't a winner than that field just be missing altogether.

**Comment by Dubman25** [comment]
You guys seem to have a solid handle on the server side stuff. I'm gonna step back from that at this point and concentrate on my bot.  You guys implement the best ideas you have, and I'll give feedback from the perspective of an advanced level participant.  Patrick, let me know if you want some cash for prizes at the tournament.

Keith
