### ISSUE TITLE
Skirmish Creation

### ISSUE THREAD

**Issue by Pabreetzio** [AiBattleground/BotWars#7]
#### For the other selection a user should be able to see a list of the public bots.

The list should be reasonably sized, so after the potential list grows to long it should be a partial list. If the list grows too long we should limit it somehow, perhaps randomly until we reach the point where we need to consider better solutions such as grouping them into categories.
##### The lists should maintain a user's privacy

We should never expose the URL of a bot unless the user who created it asks us to. We may even not want to expose consecutive primary keys for bots because that could open up potential ways a user can infer the id of a bot that is not public, rather we can create temporary references to the bots using something like a shortcode generator. The shortcodes can reference the public bot, but be changed when the privacy settings for a bot are changed.
#### The Skirmish settings should be configurable

Things like start time, and time between moves can make it easier for the battle to be viewed. Privacy settings can prevent the battle from being viewed by everyone, or allow it to be published as a public event from elsewhere in the site.
#### Once two bots are chose the user can launch a battle

The battle room should have a Signal R setup where people can watch the battle live from various machines. The URL for the battle should be a randomly generated id.

**Comment by Dubman25** [comment]
As per a previous email, Smiles is working on the Skirmish screen.

Keith

**Comment by Dubman25** [comment]
Is this an issue or an enhancement?  How are we tracking tasks?

**Comment by Pharylon** [comment]
While it's not done yet by a longshot, I did some work on this so it's more-or-less working.

**Comment by Pharylon** [comment]
OK, while there's room for improvement, I'm ready to call this done. I pulled out the main Battle View logic into a partial view so we can call it from any other views we make in the Battle Controller. The Skirmish code is now part of the Battle Controller rather than Home, but it's basically the way Patrick had it set up before. I forgot to branch this time... sorry. So it's already commited to the Master branch.
